//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hospital.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Case_relapse> Case_relapse { get; set; }
        public virtual DbSet<Case_treatment> Case_treatment { get; set; }
        public virtual DbSet<Disease> Disease { get; set; }
        public virtual DbSet<LABH_laboratory> LABH_laboratory { get; set; }
        public virtual DbSet<TOTF_comorbidity> TOTF_comorbidity { get; set; }
        public virtual DbSet<TOTF_medicine> TOTF_medicine { get; set; }
    }
}
